version: "3.9"

services:
  myapp:
    image: jenkins
    networks:
      mynetwork:

  db:
    image: postgres
    restart: always
    networks:
      mynetwork:

networks:
  mynetwork:
    name: mynetwork
